---
  - name: Apt install CLUES2 requirements in Deb system
    apt: pkg=unzip,git,wget update_cache=yes

  - name: Apt install pip in Deb
    apt: pkg=python3-pip,python3-setuptools

  - name: Set clues facts
    set_fact: CLUES_SERVER_BINARY="/usr/local/bin/cluesserver"
