- name: Set SLURM conf facts for Debian
  set_fact:
    SBATCH_BINARY: "/usr/local/bin/sbatch"
    SBATCH_BACKUP: "/usr/local/bin/sbatch.o"
    CLUES_SLURM_WRAPPER: "/usr/local/bin/clues-slurm-wrapper"
    SCONTROL_BIN: "/usr/local/bin/scontrol"
    SLURM_SERVICE: "slurmctld"
  when: ansible_os_family == "Debian"

- name: Set SLURM conf facts for CentOS
  set_fact:
    SBATCH_BINARY: "/usr/bin/sbatch"
    SBATCH_BACKUP: "/usr/bin/sbatch.o"
    CLUES_SLURM_WRAPPER: "/usr/bin/clues-slurm-wrapper"
    SCONTROL_BIN: "/usr/bin/scontrol"
  when: ansible_os_family == "RedHat"

- name: Update 'NodeName' in slurm.conf
  lineinfile: dest={{SLURM_CONF}} regexp='NodeName=' line='NodeName={{vnode_prefix}}[1-{{max_number_of_nodes|int}}] CPUs=1 State=UNKNOWN'

- name: Update 'PartitionName' in slurm.conf
  lineinfile: dest={{SLURM_CONF}} regexp='PartitionName=' line='PartitionName=debug Nodes={{vnode_prefix}}[1-{{max_number_of_nodes|int}}] Default=YES MaxTime=INFINITE State=UP'

- name: Start SLURM service
  command: slurmctld

- name: Reconfigure SLURM
  command: scontrol reconfig

- name: Set SLURM as CLUES2 LRMS
  ini_file: dest=/etc/clues2/clues2.cfg section=general option=LRMS_CLASS value=cluesplugins.slurm
  notify: restart cluesd

- name: Create SLURM plugin configuration file for CLUES2
  copy: src=/etc/clues2/conf.d/plugin-slurm.cfg-example dest=/etc/clues2/conf.d/plugin-slurm.cfg force=no
  notify: restart cluesd

- name: Set SLURM_SERVER value
  ini_file: dest=/etc/clues2/conf.d/plugin-slurm.cfg section=SLURM option=SLURM_SERVER value=slurmserver
  notify: restart cluesd

- name: Set SLURM specific config for CentOS
  ini_file: dest=/etc/clues2/conf.d/plugin-slurm.cfg section=SLURM option={{ item.option }} value="{{ item.value }}"
  notify: restart cluesd
  with_items:
    - { option: 'SLURM_PARTITION_COMMAND', value: '{{SCONTROL_BIN}} -o show partitions' }
    - { option: 'SLURM_NODES_COMMAND', value: '{{SCONTROL_BIN}} -o show nodes' }
    - { option: 'SLURM_JOBS_COMMAND', value: '{{SCONTROL_BIN}} -o show jobs' }

- name: Create sbatch script backup
  copy: src={{SBATCH_BINARY}} dest={{SBATCH_BACKUP}} mode=755 force=no

- name: Replace sbatch script with clues-slurm wrapper
  copy: src={{CLUES_SLURM_WRAPPER}} dest={{SBATCH_BINARY}}
