# CLUES PBS configuration
- set_fact: TORQUE_PATH="/var/spool/torque"
- ini_file: dest=/etc/clues2/clues2.cfg section=general option=LRMS_CLASS value=cluesplugins.pbs
  notify: restart cluesd
- copy: src=/etc/clues2/conf.d/plugin-pbs.cfg-example dest=/etc/clues2/conf.d/plugin-pbs.cfg force=no
  notify: restart cluesd
- ini_file: dest=/etc/clues2/conf.d/plugin-pbs.cfg section=PBS option=PBS_SERVER value=torqueserver
  notify: restart cluesd
- lineinfile: dest={{TORQUE_PATH}}/torque.cfg regexp=^SUBMITFILTER line='SUBMITFILTER /usr/local/bin/clues-pbs-wrapper' create=yes mode=644
- copy:
    content: |
       {% for number in range(1, ec3_max_instances|int + 1) %}
       {{vnode_prefix}}{{number}}
       {% endfor %}
    dest: "{{TORQUE_PATH}}/server_priv/nodes"

- service: name=torque-server state=stopped pattern=/usr/sbin/pbs_server
- service: name=torque-server state=started pattern=/usr/sbin/pbs_server

# Many times pbs_server does not start properly. Wait and test it again
- command: sleep 5

- service: name=torque-server state=started pattern=/usr/sbin/pbs_server
  notify: restart cluesd
